# Generated by Django 4.0.4 on 2022-04-21 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_category_alter_addcategory_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='')),
                ('name', models.CharField(max_length=50, null=True)),
                ('available', models.IntegerField(null=True)),
                ('price_of_buy', models.FloatField(null=True)),
                ('price_of_sale', models.FloatField(null=True)),
                ('date_add_product', models.DateTimeField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='AddCategory',
        ),
    ]
