# Generated by Django 4.0.4 on 2022-05-07 04:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_sale_delete_sales_alter_product_date_add_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='f_total',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='price_of_selling',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='product',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_add_product',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 7, 6, 38, 25, 855572), null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date_of_purchase',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 7, 6, 38, 25, 855572), null=True),
        ),
    ]
