# Generated by Django 4.0.4 on 2022-05-08 02:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_sale_f_total_sale_price_of_selling_sale_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addsale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=50, null=True)),
                ('price_of_selling', models.FloatField(null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('total', models.FloatField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='sale',
            name='price_of_selling',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='product',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='total',
        ),
        migrations.AlterField(
            model_name='product',
            name='date_add_product',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 8, 4, 51, 21, 696905), null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date_of_purchase',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 8, 4, 51, 21, 696905), null=True),
        ),
    ]
