# Generated by Django 4.0.4 on 2022-05-08 03:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_addsale_remove_sale_price_of_selling_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='sale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.addsale'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_add_product',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 8, 5, 2, 2, 565961), null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date_of_purchase',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 8, 5, 2, 2, 565961), null=True),
        ),
    ]
