# Generated by Django 4.0.4 on 2022-05-12 11:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_remove_sale_sale_sale_price_of_selling_sale_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_add_product',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 12, 13, 3, 27, 353484), null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date_of_purchase',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 12, 13, 3, 27, 353484), null=True),
        ),
    ]
